# Newbees API - Draft Recap - 2016

In [1]:
# import requests

# api_key = 'your_api_key'
# league_id = 'your_league_id'

# url = f'https://fantasy.espn.com/apis/v3/games/ffl/seasons/2021/segments/0/leagues/{league_id}?view=kona_player_info'

# headers = {
#     'Content-Type': 'application/json',
#     'Authorization': f'Basic {api_key}'
# }

# response = requests.get(url, headers=headers)

# if response.status_code == 200:
#     players = response.json()['players']
#     print(players)
# else:
#     print(f'Error {response.status_code}: {response.reason}')

In [2]:
import requests
import pandas as pd

In [3]:
espn_cookies = {'swid': '{9B9225D3-7D25-467E-9DA5-B437D394DFEE}',
 'espn_s2': 'AEAKw5MYW+sW/bnyJx6OsTV14BQPeFtF3CV5kQgoK/tokqPjYL8W2rBry/tk1w1fSiWOQr9134Q18ryX6IF2MhtbeqxdvUPpZFQLXjI9SmGCXLlcAyG2jDOKy4O9U6JPInt8v2nXVnlc++YY08DpN4E3a88ptYSRhbMWx/FuTElQdfyE9aPZ+RrZncTDFnnEr3txWVQSTPtUZ7IZ/584HTRCRRFUlegZqnMgNdNnWllmhovYaQS76HKpHM1CgbZruV5Q1QJDaz97VsbAwzXH1Ysbgz2hDWNjM3GKOwI8aWDItw'}

In [4]:
# Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

In [5]:
url = 'https://fantasy.espn.com/apis/v3/games/ffl/leagueHistory/339188?view=mDraftDetail&view=mSettings&view=mTeam&view=modular&view=mNav&seasonId=2016'

In [6]:
headers = {
 'Connection': 'keep-alive',
 'Accept': 'application/json, text/plain, */*',
 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36',
}

In [7]:
r = requests.get(url, headers=headers, cookies=espn_cookies)
espn_raw_data = r.json()

In [8]:
espn_draft_detail = espn_raw_data[0]
draft_picks = espn_draft_detail['draftDetail']['picks']

In [9]:
df = pd.DataFrame(draft_picks)

In [10]:
df

,autoDraftTypeId,bidAmount,id,keeper,lineupSlotId,memberId,nominatingTeamId,overallPickNumber,owningTeamIds,playerId,reservedForKeeper,roundId,roundPickNumber,teamId,tradeLocked
0,0,0,1,False,0,3436600c-3252-4b39-a933-1f7beead9084,0,1,[2],13994,False,1,1,2,False
1,0,0,2,False,0,3436600c-3252-4b39-a933-1f7beead9084,0,2,[6],8439,False,1,2,6,False
2,0,0,3,False,4,3436600c-3252-4b39-a933-1f7beead9084,0,3,[13],13934,False,1,3,13,False
3,0,0,4,False,4,3436600c-3252-4b39-a933-1f7beead9084,0,4,[3],13982,False,1,4,3,False
4,0,0,5,False,4,3436600c-3252-4b39-a933-1f7beead9084,0,5,[5],16733,False,1,5,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,0,0,156,False,17,3436600c-3252-4b39-a933-1f7beead9084,0,156,[5],4333,False,16,6,5,False
156,0,0,157,False,20,3436600c-3252-4b39-a933-1f7beead9084,0,157,[3],12601,False,16,7,3,False
157,0,0,158,False,16,3436600c-3252-4b39-a933-1f7beead9084,0,158,[13],-16017,False,16,8,13,False
158,0,0,159,False,20,3436600c-3252-4b39-a933-1f7beead9084,0,159,[6],14402,False,16,9,6,False
159,0,0,160,False,20,3436600c-3252-4b39-a933-1f7beead9084,0,160,[2],4527,False,16,10,2,False

In [11]:
draft_df = df[['overallPickNumber', 'playerId', 'teamId']]

In [12]:
draft_df

     overallPickNumber  playerId  teamId
0                    1     13994       2
1                    2      8439       6
2                    3     13934      13
3                    4     13982       3
4                    5     16733       5
..                 ...       ...     ...
155                156      4333       5
156                157     12601       3
157                158    -16017      13
158                159     14402       6
159                160      4527       2

[160 rows x 3 columns]

In [13]:
player_url = 'https://fantasy.espn.com/apis/v3/games/ffl/seasons/2016/players?scoringPeriodId=0&view=players_wl'

In [14]:
# x-fantasy-filter: {“filterActive”:null}
# x-fantasy-platform: kona-PROD-d8fba14d942cfef237ca6d6cc3ba9de27b91ae37
# x-fantasy-source: kona

In [15]:
headers = {
 'Connection': 'keep-alive',
 'Accept': 'application/json, text/plain, */*',
 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
 'x-fantasy-filter': '{"filterActive":null}',
 'x-fantasy-platform': 'kona-PROD-1dc40132dc2070ef47881dc95b633e62cebc9913',
 'x-fantasy-source': 'kona'
}

In [16]:
r = requests.get(player_url, cookies=espn_cookies, headers=headers)
player_data = r.json()

In [17]:
df = pd.DataFrame(player_data)
# get only needed columns for players
player_df = df[['defaultPositionId','fullName','id','proTeamId']]
# rename id column for inner join
player_df.rename(columns = {'id':'player_id'}, inplace = True)

C:\Users\TechnologyDataServic\AppData\Local\Temp\ipykernel_22720\3134529855.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  player_df.rename(columns = {'id':'player_id'}, inplace = True)

In [18]:
player_df

      defaultPositionId         fullName  player_id  proTeamId
0                     2  Fozzy Whittaker      15755         29
1                     3    Jeremy Kelley      15758          3
2                     2   Austin Johnson      15765         27
3                    12        Tye Smith    2588098         10
4                     4     Darren Fells      15773          8
...                 ...              ...        ...        ...
5077                  3      Lance Lewis      15741         18
5078                 11     Jordan Hicks    2514270         21
5079                  9      Oren Wilson      15747          0
5080                  9    Bobby Skinner      15748          0
5081                  2       Jeff Demps      15749         11

[5082 rows x 4 columns]

In [19]:
season_id = '2016'

url = "https://fantasy.espn.com/apis/v3/games/ffl/seasons/{}?view=proTeamSchedules_wl".format(season_id)
r = requests.get(url, cookies=espn_cookies)
team_data = r.json()
team_names = team_data['settings']['proTeams']
df = pd.DataFrame(team_names)
# get only needed columns for teams
team_df = df[['id', 'location', 'name']]
team_df["team name"] = team_df['location'].astype(str) +" "+ team_df["name"]
# rename in column
team_df.rename(columns = {'id':'team_id'}, inplace = True)

C:\Users\TechnologyDataServic\AppData\Local\Temp\ipykernel_22720\3923662058.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_df["team name"] = team_df['location'].astype(str) +" "+ team_df["name"]
C:\Users\TechnologyDataServic\AppData\Local\Temp\ipykernel_22720\3923662058.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_df.rename(columns = {'id':'team_id'}, inplace = True)

In [20]:
team_df

    team_id       location        name             team name
0        11   Indianapolis       Colts    Indianapolis Colts
1        12    Kansas City      Chiefs    Kansas City Chiefs
2        13        Oakland     Raiders       Oakland Raiders
3        14    Los Angeles        Rams      Los Angeles Rams
4        15          Miami    Dolphins        Miami Dolphins
5        16      Minnesota     Vikings     Minnesota Vikings
6        17    New England    Patriots  New England Patriots
7        18    New Orleans      Saints    New Orleans Saints
8        19       New York      Giants       New York Giants
9        20       New York        Jets         New York Jets
10       21   Philadelphia      Eagles   Philadelphia Eagles
11       22        Arizona   Cardinals     Arizona Cardinals
12       23     Pittsburgh    Steelers   Pittsburgh Steelers
13       24      San Diego    Chargers    San Diego Chargers
14       25  San Francisco       49ers   San Francisco 49ers
15       26        Seattle    Seahawks      Seattle Seahawks
16       27      Tampa Bay  Buccaneers  Tampa Bay Buccaneers
17       28     Washington    Redskins   Washington Redskins
18       29       Carolina    Panthers     Carolina Panthers
19       30   Jacksonville     Jaguars  Jacksonville Jaguars
20       33      Baltimore      Ravens      Baltimore Ravens
21       34        Houston      Texans        Houston Texans
22        0                         FA                    FA
23        1        Atlanta     Falcons       Atlanta Falcons
24        2        Buffalo       Bills         Buffalo Bills
25        3        Chicago       Bears         Chicago Bears
26        4     Cincinnati     Bengals    Cincinnati Bengals
27        5      Cleveland      Browns      Cleveland Browns
28        6         Dallas     Cowboys        Dallas Cowboys
29        7         Denver     Broncos        Denver Broncos
30        8        Detroit       Lions         Detroit Lions
31        9      Green Bay     Packers     Green Bay Packers
32       10      Tennessee      Titans      Tennessee Titans

In [21]:
# merge tables together and save into a new df
df2 = pd.merge(draft_df, player_df, how="inner", left_on="playerId", right_on = "player_id")
# merge tables together and save into a new df
final_df = pd.merge(df2, team_df, how="inner", left_on="proTeamId", right_on = "team_id")

In [22]:
final_df

,overallPickNumber,playerId,teamId,defaultPositionId,fullName,player_id,proTeamId,team_id,location,name,team name
0,1,13994,2,1,Cam Newton,13994,29,29,Carolina,Panthers,Carolina Panthers
1,34,10475,1,4,Greg Olsen,10475,29,29,Carolina,Panthers,Carolina Panthers
2,42,11247,6,2,Jonathan Stewart,11247,29,29,Carolina,Panthers,Carolina Panthers
3,49,16730,12,3,Kelvin Benjamin,16730,29,29,Carolina,Panthers,Carolina Panthers
4,116,-16029,5,16,Panthers D/ST,-16029,29,29,Carolina,Panthers,Carolina Panthers
...,...,...,...,...,...,...,...,...,...,...,...
155,122,2978929,6,3,Corey Coleman,2978929,5,5,Cleveland,Browns,Cleveland Browns
156,137,17133,3,2,Isaiah Crowell,17133,5,5,Cleveland,Browns,Cleveland Browns
157,81,11788,2,2,Danny Woodhead,11788,33,33,Baltimore,Ravens,Baltimore Ravens
158,127,15683,1,5,Justin Tucker,15683,33,33,Baltimore,Ravens,Baltimore Ravens
159,157,12601,3,3,Mike Wallace,12601,33,33,Baltimore,Ravens,Baltimore Ravens

In [23]:
position_mapping = {
 1: 'QB',
 2: 'RB',
 3: 'WR',
 4: 'TE',
 5: 'K',
 16: 'D/ST'
}

In [24]:
# rename columns and map values for easier consumption. Save to new dataframe
league_draft = final_df.replace({"defaultPositionId": position_mapping})

In [25]:
league_draft

,overallPickNumber,playerId,teamId,defaultPositionId,fullName,player_id,proTeamId,team_id,location,name,team name
0,1,13994,2,QB,Cam Newton,13994,29,29,Carolina,Panthers,Carolina Panthers
1,34,10475,1,TE,Greg Olsen,10475,29,29,Carolina,Panthers,Carolina Panthers
2,42,11247,6,RB,Jonathan Stewart,11247,29,29,Carolina,Panthers,Carolina Panthers
3,49,16730,12,WR,Kelvin Benjamin,16730,29,29,Carolina,Panthers,Carolina Panthers
4,116,-16029,5,D/ST,Panthers D/ST,-16029,29,29,Carolina,Panthers,Carolina Panthers
...,...,...,...,...,...,...,...,...,...,...,...
155,122,2978929,6,WR,Corey Coleman,2978929,5,5,Cleveland,Browns,Cleveland Browns
156,137,17133,3,RB,Isaiah Crowell,17133,5,5,Cleveland,Browns,Cleveland Browns
157,81,11788,2,RB,Danny Woodhead,11788,33,33,Baltimore,Ravens,Baltimore Ravens
158,127,15683,1,K,Justin Tucker,15683,33,33,Baltimore,Ravens,Baltimore Ravens
159,157,12601,3,WR,Mike Wallace,12601,33,33,Baltimore,Ravens,Baltimore Ravens

In [26]:
newbees_teams = {
1: 'KIRK',
2: 'COLL',
3: 'CD',
5: 'CRIN',
6: 'SHIT',
11: 'SCHM',
12: 'HENE',
13: 'VU',
14: 'TKIRK',
16: 'MILL'
}

In [27]:
# rename columns and map values for easier consumption. Save to new dataframe
league_draft = league_draft.replace({"teamId": newbees_teams})

In [28]:
league_draft

,overallPickNumber,playerId,teamId,defaultPositionId,fullName,player_id,proTeamId,team_id,location,name,team name
0,1,13994,COLL,QB,Cam Newton,13994,29,29,Carolina,Panthers,Carolina Panthers
1,34,10475,KIRK,TE,Greg Olsen,10475,29,29,Carolina,Panthers,Carolina Panthers
2,42,11247,SHIT,RB,Jonathan Stewart,11247,29,29,Carolina,Panthers,Carolina Panthers
3,49,16730,HENE,WR,Kelvin Benjamin,16730,29,29,Carolina,Panthers,Carolina Panthers
4,116,-16029,CRIN,D/ST,Panthers D/ST,-16029,29,29,Carolina,Panthers,Carolina Panthers
...,...,...,...,...,...,...,...,...,...,...,...
155,122,2978929,SHIT,WR,Corey Coleman,2978929,5,5,Cleveland,Browns,Cleveland Browns
156,137,17133,CD,RB,Isaiah Crowell,17133,5,5,Cleveland,Browns,Cleveland Browns
157,81,11788,COLL,RB,Danny Woodhead,11788,33,33,Baltimore,Ravens,Baltimore Ravens
158,127,15683,KIRK,K,Justin Tucker,15683,33,33,Baltimore,Ravens,Baltimore Ravens
159,157,12601,CD,WR,Mike Wallace,12601,33,33,Baltimore,Ravens,Baltimore Ravens

In [29]:
for item in espn_draft_detail['members']:
    print(item)

{'displayName': 'cuonga', 'firstName': 'Cuong', 'id': '{0654860E-F9F8-11D3-820C-00A0C9E58E2D}', 'isLeagueCreator': False, 'isLeagueManager': False, 'lastName': 'Vu'}
{'displayName': 'Pat Patriot54', 'firstName': 'Jess', 'id': '{18D352BB-349D-4928-8025-99297946EB2C}', 'isLeagueCreator': False, 'isLeagueManager': False, 'lastName': 'Collier'}
{'displayName': 'Mark405100', 'firstName': 'Mark', 'id': '{5259BD1C-8123-47BA-9EFA-F7C313EB5203}', 'isLeagueCreator': False, 'isLeagueManager': False, 'lastName': 'Foltz'}
{'displayName': 'dlugolinski13', 'firstName': 'chris', 'id': '{5F0A4D57-E1EB-4162-A39A-C0EED17FABF3}', 'isLeagueCreator': False, 'isLeagueManager': False, 'lastName': 'dlugolinski'}
{'displayName': 'samthelion44', 'firstName': 'jeff', 'id': '{8CEB3D56-5C06-4697-8A37-FB34216EF437}', 'isLeagueCreator': False, 'isLeagueManager': False, 'lastName': 'miller'}
{'displayName': 'Timothy-Kirk', 'firstName': 'Timothy', 'id': '{9B9225D3-7D25-467E-9DA5-B437D394DFEE}', 'isLeagueCreator': False, 'isLeagueManager': False, 'lastName': 'Kirk'}
{'displayName': 'busketneck1', 'firstName': 'craig', 'id': '{BFD238EA-3CB8-4C66-934B-DF61CB2BD66F}', 'isLeagueCreator': False, 'isLeagueManager': False, 'lastName': 'rinaldo'}
{'displayName': 'Hendigidy1327', 'firstName': 'Frank', 'id': '{C1D34E02-0E94-4BEF-BA38-FF2BA16051B1}', 'isLeagueCreator': False, 'isLeagueManager': False, 'lastName': 'Henegar'}
{'displayName': 'schmerr13', 'firstName': 'scott', 'id': '{EF99C28F-C386-49E9-A358-EBB70C462072}', 'isLeagueCreator': False, 'isLeagueManager': False, 'lastName': 'schmerr'}
{'displayName': 'ryanlawrencekirk', 'firstName': 'Ryan', 'id': '{F9C308E1-95B7-4F5A-AB25-18B2CC73BE68}', 'isLeagueCreator': True, 'isLeagueManager': False, 'lastName': 'Kirk'}

In [30]:
for item in espn_draft_detail:
    print(item)

draftDetail
gameId
id
members
scoringPeriodId
seasonId
segmentId
settings
status
teams

In [31]:
for item in espn_draft_detail['teams']:
    print(item['id'], item['abbrev'])

1 KIRK
2 COLL
3 CD
5 CRIN
6 SHIT
11 SCHM
12 HENE
13 VU
14 KIRK
16 MILL

In [ ]:
print(espn_draft_detail['scoringPeriodId'])

In [35]:
tkirk = league_draft[league_draft['teamId'] == 'TKIRK']

tkirk.sort_values(by=['overallPickNumber'])

,overallPickNumber,playerId,teamId,defaultPositionId,fullName,player_id,proTeamId,team_id,location,name,team name
33,8,3051392,TKIRK,RB,Ezekiel Elliott,3051392,6,6,Dallas,Cowboys,Dallas Cowboys
18,13,16944,TKIRK,RB,Devonta Freeman,16944,1,1,Atlanta,Falcons,Atlanta Falcons
105,28,13981,TKIRK,RB,Mark Ingram,13981,18,18,New Orleans,Saints,New Orleans Saints
97,33,16725,TKIRK,WR,Sammy Watkins,16725,2,2,Buffalo,Bills,Buffalo Bills
136,48,16790,TKIRK,WR,Jarvis Landry,16790,15,15,Miami,Dolphins,Miami Dolphins
84,53,12579,TKIRK,WR,Jeremy Maclin,12579,12,12,Kansas City,Chiefs,Kansas City Chiefs
60,68,14908,TKIRK,WR,Michael Floyd,14908,17,17,New England,Patriots,New England Patriots
54,73,5528,TKIRK,WR,Larry Fitzgerald,5528,22,22,Arizona,Cardinals,Arizona Cardinals
143,88,2576336,TKIRK,RB,Ameer Abdullah,2576336,8,8,Detroit,Lions,Detroit Lions
120,93,12563,TKIRK,WR,Michael Crabtree,12563,13,13,Oakland,Raiders,Oakland Raiders
94,108,15835,TKIRK,TE,Zach Ertz,15835,21,21,Philadelphia,Eagles,Philadelphia Eagles
98,113,14163,TKIRK,QB,Tyrod Taylor,14163,2,2,Buffalo,Bills,Buffalo Bills
121,128,16757,TKIRK,QB,Derek Carr,16757,13,13,Oakland,Raiders,Oakland Raiders
151,133,12699,TKIRK,TE,Zach Miller,12699,3,3,Chicago,Bears,Chicago Bears
88,148,-16012,TKIRK,D/ST,Chiefs D/ST,-16012,12,12,Kansas City,Chiefs,Kansas City Chiefs
36,153,14322,TKIRK,K,Dan Bailey,14322,6,6,Dallas,Cowboys,Dallas Cowboys

In [36]:
mill = league_draft[league_draft['teamId'] == 'MILL']

mill.sort_values(by=['overallPickNumber'])

,overallPickNumber,playerId,teamId,defaultPositionId,fullName,player_id,proTeamId,team_id,location,name,team name
47,10,15795,MILL,WR,DeAndre Hopkins,15795,34,34,Houston,Texans,Houston Texans
51,11,2508176,MILL,RB,David Johnson,2508176,22,22,Arizona,Cardinals,Arizona Cardinals
114,30,15818,MILL,WR,Keenan Allen,15818,24,24,San Diego,Chargers,San Diego Chargers
111,31,16040,MILL,RB,C.J. Anderson,16040,7,7,Denver,Broncos,Denver Broncos
9,50,14053,MILL,WR,Randall Cobb,14053,9,9,Green Bay,Packers,Green Bay Packers
30,51,15920,MILL,RB,Latavius Murray,15920,16,16,Minnesota,Vikings,Minnesota Vikings
103,70,8479,MILL,RB,Frank Gore,8479,11,11,Indianapolis,Colts,Indianapolis Colts
24,71,5526,MILL,QB,Eli Manning,5526,19,19,New York,Giants,New York Giants
74,90,17177,MILL,WR,Allen Hurns,17177,30,30,Jacksonville,Jaguars,Jacksonville Jaguars
116,91,5362,MILL,TE,Antonio Gates,5362,24,24,San Diego,Chargers,San Diego Chargers
86,110,16020,MILL,RB,Spencer Ware,16020,12,12,Kansas City,Chiefs,Kansas City Chiefs
81,111,-16026,MILL,D/ST,Seahawks D/ST,-16026,26,26,Seattle,Seahawks,Seattle Seahawks
144,130,16732,MILL,TE,Eric Ebron,16732,8,8,Detroit,Lions,Detroit Lions
49,131,-16034,MILL,D/ST,Texans D/ST,-16034,34,34,Houston,Texans,Houston Texans
146,150,12483,MILL,QB,Matthew Stafford,12483,8,8,Detroit,Lions,Detroit Lions
12,151,10636,MILL,K,Mason Crosby,10636,9,9,Green Bay,Packers,Green Bay Packers

In [49]:
for item in espn_draft_detail['teams'][0]:
    print(item)

K
I
R
K